FROM nvcr.io/nvidia/pytorch:26.06-py3

# Set the working directory inside the container
WORKDIR /workspace

# Copy the local main.py file into the container
COPY main.py .

# Run the script when the container starts
CMD ["python", "main.py"]

