services:
  gpu-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nvidia_jupyter_workspace
    volumes:
      - .:/workspace
    ports:
      - "8888:8888" # Maps server_ip:8888 to container:8888
    shm_size: '16gb' # Crucial for PyTorch Dataloaders to prevent shared memory crashes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Use all available GPUs
              capabilities: [gpu]
